[package]
executable = "1password"
homepage = "https://1password.com/"
description = "More than a password manager."

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed 1password"

is-installed.program = "command"
is-installed.args = ["-v", "1password"]
is-installed.redirect.stderr-to = "/dev/null"
