[package]
executable = "cargo-binstall"
homepage = "https://github.com/cargo-bins/cargo-binstall"
description = "Binary installation for rust projects"

[command-set.curl]
install.program = "curl"
install.args = [
  "-L",
  "--proto",
  "=https",
  "--tlsv1.2",
  "-sSf",
  "https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh",
]
install.pipe = "bash"

is-installed.program = "command"
is-installed.args = ["-v", "cargo-binstall"]
is-installed.redirect.stderr-to = "/dev/null"
