[package]
executable = "cmake-language-server"
homepage = "https://github.com/regen100/cmake-language-server"
description = "CMake LSP Implementation"

[command-set.pipx]
install = "pipx install cmake-language-server"

is-installed.program = "command"
is-installed.args = ["-v", "cmake-language-server"]
is-installed.redirect.stderr-to = "/dev/null"
