[package]
executable = "dua"
homepage = "https://github.com/Byron/dua-cli"
description = "View disk space usage and delete unwanted data, fast."

[command-sets.default]
install = "brew install dua-cli"

is-installed.program = "command"
is-installed.args = ["-v", "dua"]
is-installed.redirect.stderr-to = "/dev/null"
