[package]
executable = "fastfetch"
homepage = "https://github.com/fastfetch-cli/fastfetch"
description = "Like neofetch, but much faster because written mostly in C."

[command-set.brew]
install = "brew install fastfetch"

is-installed.program = "command"
is-installed.args = ["-v", "fastfetch"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed fastfetch"

is-installed.program = "command"
is-installed.args = ["-v", "fastfetch"]
is-installed.redirect.stderr-to = "/dev/null"
