[package]
description = "🚀 Fast and simple Node.js version manager, built in Rust"
version = "0.1.0"
dependencies = []
homepage = "https://github.com/Schniz/fnm"
notes = """
The fnm installer says it'll update your shell rc files. FWIW, I don't think that's
the case if you install using `brew`.
"""

[command-set]
install.shell = "curl -fsSL https://fnm.vercel.app/install | bash"
is-installed.shell = "command -v fnm"
