[package]
executable = "fzf"
homepage = "https://github.com/junegunn/fzf"
description = "🌸 A command-line fuzzy finder"

[command-set.brew]
install = "brew install fzf"

is-installed.program = "command"
is-installed.args = ["-v", "fzf"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman -S --needed --noconfirm fzf"

is-installed.program = "command"
is-installed.args = ["-v", "fzf"]
is-installed.redirect.stderr-to = "/dev/null"
