[package]
executable = "git"
homepage = "https://git-scm.com/"
description = """
Git is a free and open source distributed version control system designed to
handle everything from small to very large projects with speed and efficiency.
"""

[command-sets.default]
install = "brew install git"

is-installed.program = "command"
is-installed.args = ["-v", "git"]
is-installed.redirect.stderr-to = "/dev/null"
