[package]
executable = "gpg"
homepage = "https://gnupg.org/"
description = """
 GnuPG is a complete and free implementation of the OpenPGP standard as defined
by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data
and communications; it features a versatile key management system, along with
access modules for all kinds of public key directories. GnuPG, also known as
GPG, is a command line tool with features for easy integration with other
applications. A wealth of frontend applications and libraries are available.
GnuPG also provides support for S/MIME and Secure Shell (ssh).
"""

[command-set.default]
install = "brew install gpg2"

is-installed.program = "command"
is-installed.args = ["-v", "gpg2"]
is-installed.redirect.stderr-to = "/dev/null"
