[package]
executable = "jq"
homepage = "https://github.com/jqlang/jq"
description = "Command-line JSON processor"

[command-set.brew]
install = "brew install jq"

is-installed.program = "command"
is-installed.args = ["-v", "jq"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman -S --noconfirm --needed jq"

is-installed.program = "command"
is-installed.args = ["-v", "jq"]
is-installed.redirect.stderr-to = "/dev/null"
