[package]
executable = "jq"
homepage = "https://github.com/jqlang/jq"
description = "Command-line JSON processor"

[command-sets.default]
install = "brew install jq"

is-installed.program = "command"
is-installed.args = ["-v", "jq"]
is-installed.redirect.stderr-to = "/dev/null"
