[package]
executable = "lazygit"
homepage = "https://github.com/jesseduffield/lazygit/"
description = "simple terminal UI for git commands"

[command-set.brew]
install = "brew install lazygit"

is-installed.program = "command"
is-installed.args = ["-v", "lazygit"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed lazygit"

is-installed.program = "command"
is-installed.args = ["-v", "lazygit"]
is-installed.redirect.stderr-to = "/dev/null"
