[package]
executable = "mcfly"
homepage = "https://github.com/cantino/mcfly"
description = "Fly through your shell history. Great Scott!"

[command-sets.default]
install = "brew install mcfly"

is-installed.program = "command"
is-installed.args = ["-v", "mcfly"]
is-installed.redirect.stderr-to = "/dev/null"
