[package]
executable = "nvim"
homepage = "https://neovim.io/"
description = "hyperextensible Vim-based text editor"

[command-set.brew]
install = "brew install neovim"

is-installed.program = "command"
is-installed.args = ["-v", "nvim"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed neovim python-pynvim wl-clipboard"

is-installed.program = "command"
is-installed.args = ["-v", "nvim"]
is-installed.redirect.stderr-to = "/dev/null"
