[package]
executable = "pipx"
homepage = "https://github.com/pypa/pipx"
description = """
Install and Run Python Applications in Isolated Environments
"""

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed python-pipx"

is-installed.program = "command"
is-installed.args = ["-v", "pipx"]
is-installed.redirect.stderr-to = "/dev/null"
