[package]
executable = "prettier"
homepage = "https://prettier.io/"
description = "An opinionated code formatter"
notes = """
What about using dprint?
"""

[command-set.npm]
install = "npm install -g prettier"

is-installed.program = "command"
is-installed.args = ["-v", "prettier"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed prettier"

is-installed.program = "command"
is-installed.args = ["-v", "prettier"]
is-installed.redirect.stderr-to = "/dev/null"
