[package]
executable = "solargraph"
homepage = "https://solargraph.org/"
description = """
Solargraph is a Ruby gem that provides intellisense features through Microsoft's
language server protocol.
"""

[command-set.gem]
install = "gem install solargraph"

is-installed.program = "command"
is-installed.args = ["-v", "solargraph"]
is-installed.redirect.stderr-to = "/dev/null"
