[package]
executable = "starship"
homepage = "https://starship.rs/"
description = """
The minimal, blazing-fast, and infinitely customizable prompt for any shell!
"""

[command-set.default]
install = "brew install starship"

is-installed.program = "command"
is-installed.args = ["-v", "starship"]
is-installed.redirect.stderr-to = "/dev/null"
