[package]
executable = "tree-sitter"
homepage = "https://tree-sitter.github.io/tree-sitter/"
description = """
Tree-sitter is a parser generator tool and an incremental parsing library. It can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited.
"""

[command-sets.default]
install = "brew install tree-sitter"

is-installed.program = "command"
is-installed.args = ["-v", "tree-sitter"]
is-installed.redirect.stderr-to = "/dev/null"
