[package]
executable = "typescript-language-server"
homepage = "https://github.com/typescript-language-server/typescript-language-server"
description = "TypeScript & JavaScript Language Server"
notes = """
Prefer the `npm` version since OS PMs will install Node.
"""

[command-set.npm]
install = "npm install --global typescript-language-server"

is-installed.program = "command"
is-installed.args = ["-v", "typescript-language-server"]
is-installed.redirect.stderr-to = "/dev/null"

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed typescript-language-server"

is-installed.program = "command"
is-installed.args = ["-v", "typescript-language-server"]
is-installed.redirect.stderr-to = "/dev/null"
