[package]
executable = "vim-language-server"
homepage = "https://github.com/iamcco/vim-language-server"
description = "VImScript language server, LSP for vim script"
notes = """
Since this depends on node, it'd probably be better to just install via npm?
"""

[command-set.pacman]
install = "sudo pacman --sync --noconfirm --needed vim-language-server"

is-installed.program = "command"
is-installed.args = ["-v", "vim-language-server"]
is-installed.redirect.stderr-to = "/dev/null"
