[package]
executable = "zoxide"
homepage = "https://github.com/ajeetdsouza/zoxide"
description = "A smarter cd command. Supports all major shells."

[command-sets.default]
install = "brew install zoxide"

is-installed.program = "command"
is-installed.args = ["-v", "zoxide"]
is-installed.redirect.stderr-to = "/dev/null"
