[package]
executable = "zr"
homepage = "https://github.com/jedahan/zr"
description = "zsh plugin manager written in rust"

[command-set.cargo]
install = "cargo binstall --no-confirm zr"

is-installed.program = "command"
is-installed.args = ["-v", "zr"]
is-installed.redirect.stderr-to = "/dev/null"
